apiVersion: apps/v1
kind: Deployment
metadata:
 name: mytestflaskapp
 labels:
    app: testflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testflask
  template:
    metadata:
      labels:
        app: testflask
    spec:
      containers:
        - name: testflask
          image: docker.io/DOCKER_ID/testflask:v0.1.0          
          ports:
            - name: myport
              containerPort: 8888
      imagePullSecrets:
        - name: regcred